# Generated by Django 3.2.7 on 2021-09-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
