# Generated by Django 3.2.7 on 2021-09-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggieapp', '0002_auto_20210920_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.IntegerField(),
        ),
    ]
