# Generated by Django 3.2.7 on 2021-09-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggieapp', '0004_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='subtotal',
            field=models.IntegerField(),
        ),
    ]
