# Generated by Django 3.2.7 on 2021-09-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggieapp', '0006_auto_20210923_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
