# Generated by Django 3.2.7 on 2021-09-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggieapp', '0008_alter_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='products',
        ),
    ]
